version: '3.7'
services:
  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      - MYSQL_USER=rita
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=app
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

  postgresql:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=rita
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=app